# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock

# 2. Installed Gems
plugins:
- jekyll-paginate

# 3. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: page:num # jekyll-paginate > blog page

# 4. Jekyll settings
sass:
style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: "Ruzies' Feed" # Needed for Siteleaf
    output: true # Show the output
    description: "This is my personal blog, follow it for various hidden secrets." # The post list page content

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Ruzies' Feed" # Site name or title
logo: "/assets/logo.png" # Site logo
# favicon: "/favicon.ico" # Uncomment to add custom favicon, or leave as is to use site logo
description: "Get free of cost feeds" # Site description and default description
url: "" # Site url
baseurl: ""
lang: en-GB
